fp=int(input())
fd=int(input())
fs=int(input())
sp=int(input())
sd=int(input())
ss=int(input())
ap=int(input())
ad=int(input())
ash=int(input())
fdisc=float((fp*fd)/100)
fcost=int(fp-fdisc+fs)
sdisc=float((sp*sd)/100)
scost=int(sp-sdisc+ss)
adisc=float((ap*ad)/100)
acost=int(ap-adisc+ash)
print("In Flipkart: Rs.",fcost,sep="")
print("In Snapdeal: Rs.",scost,sep="")
print("In Amazon: Rs.",acost,sep="")
if fcost<=scost and fcost<=acost:
  print("Choose Flipkart")
elif scost<=acost:
  print("Choose Snapdeal")
else:
  print("Choose Amazon")
